# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'audioLabelMainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.2.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtOpenGLWidgets import QOpenGLWidget
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QLabel, QListWidget,
    QListWidgetItem, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QSlider, QSpacerItem, QSplitter,
    QStatusBar, QToolButton, QVBoxLayout, QWidget)
from glwidget import GLWidget
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(838, 569)
        icon = QIcon()
        icon.addFile(u":/icons/resources/owl.svg", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.actionOpenFile = QAction(MainWindow)
        self.actionOpenFile.setObjectName(u"actionOpenFile")
        self.actionOpenAudioFolder = QAction(MainWindow)
        self.actionOpenAudioFolder.setObjectName(u"actionOpenAudioFolder")
        self.action12 = QAction(MainWindow)
        self.action12.setObjectName(u"action12")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSaveAs = QAction(MainWindow)
        self.actionSaveAs.setObjectName(u"actionSaveAs")
        self.action0s = QAction(MainWindow)
        self.action0s.setObjectName(u"action0s")
        self.action0s.setCheckable(True)
        self.action60s = QAction(MainWindow)
        self.action60s.setObjectName(u"action60s")
        self.action60s.setCheckable(True)
        self.action120s = QAction(MainWindow)
        self.action120s.setObjectName(u"action120s")
        self.action120s.setCheckable(True)
        self.action180s = QAction(MainWindow)
        self.action180s.setObjectName(u"action180s")
        self.action180s.setCheckable(True)
        self.action180s.setChecked(False)
        self.action300s = QAction(MainWindow)
        self.action300s.setObjectName(u"action300s")
        self.action300s.setCheckable(True)
        self.actionUserDefined = QAction(MainWindow)
        self.actionUserDefined.setObjectName(u"actionUserDefined")
        self.actionUserDefined.setCheckable(True)
        self.actionGetStarted = QAction(MainWindow)
        self.actionGetStarted.setObjectName(u"actionGetStarted")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionOpenAudioFiles = QAction(MainWindow)
        self.actionOpenAudioFiles.setObjectName(u"actionOpenAudioFiles")
        self.actionOpenJsonFile = QAction(MainWindow)
        self.actionOpenJsonFile.setObjectName(u"actionOpenJsonFile")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.action0point25 = QAction(MainWindow)
        self.action0point25.setObjectName(u"action0point25")
        self.action0point25.setCheckable(True)
        self.action0point5 = QAction(MainWindow)
        self.action0point5.setObjectName(u"action0point5")
        self.action0point5.setCheckable(True)
        self.action0point75 = QAction(MainWindow)
        self.action0point75.setObjectName(u"action0point75")
        self.action0point75.setCheckable(True)
        self.action1point0 = QAction(MainWindow)
        self.action1point0.setObjectName(u"action1point0")
        self.action1point0.setCheckable(True)
        self.action1point25 = QAction(MainWindow)
        self.action1point25.setObjectName(u"action1point25")
        self.action1point25.setCheckable(True)
        self.action1point5 = QAction(MainWindow)
        self.action1point5.setObjectName(u"action1point5")
        self.action1point5.setCheckable(True)
        self.action1point75 = QAction(MainWindow)
        self.action1point75.setObjectName(u"action1point75")
        self.action1point75.setCheckable(True)
        self.action2point0 = QAction(MainWindow)
        self.action2point0.setObjectName(u"action2point0")
        self.action2point0.setCheckable(True)
        self.action2point5 = QAction(MainWindow)
        self.action2point5.setObjectName(u"action2point5")
        self.action2point5.setCheckable(True)
        self.action5s = QAction(MainWindow)
        self.action5s.setObjectName(u"action5s")
        self.action5s.setCheckable(True)
        self.action1s = QAction(MainWindow)
        self.action1s.setObjectName(u"action1s")
        self.action1s.setCheckable(True)
        self.action3s = QAction(MainWindow)
        self.action3s.setObjectName(u"action3s")
        self.action3s.setCheckable(True)
        self.action0_5 = QAction(MainWindow)
        self.action0_5.setObjectName(u"action0_5")
        self.action0_5.setCheckable(True)
        self.action0_75 = QAction(MainWindow)
        self.action0_75.setObjectName(u"action0_75")
        self.action1_0 = QAction(MainWindow)
        self.action1_0.setObjectName(u"action1_0")
        self.action1_0.setCheckable(True)
        self.action1_25 = QAction(MainWindow)
        self.action1_25.setObjectName(u"action1_25")
        self.action1_75 = QAction(MainWindow)
        self.action1_75.setObjectName(u"action1_75")
        self.action1_5 = QAction(MainWindow)
        self.action1_5.setObjectName(u"action1_5")
        self.action1_5.setCheckable(True)
        self.action2_0 = QAction(MainWindow)
        self.action2_0.setObjectName(u"action2_0")
        self.action2_0.setCheckable(True)
        self.action2_5 = QAction(MainWindow)
        self.action2_5.setObjectName(u"action2_5")
        self.action10s = QAction(MainWindow)
        self.action10s.setObjectName(u"action10s")
        self.action10s.setCheckable(True)
        self.action30s = QAction(MainWindow)
        self.action30s.setObjectName(u"action30s")
        self.action30s.setCheckable(True)
        self.actionCurrentItemOnce = QAction(MainWindow)
        self.actionCurrentItemOnce.setObjectName(u"actionCurrentItemOnce")
        self.actionCurrentItemOnce.setCheckable(True)
        self.actionCurrentItemInLoop = QAction(MainWindow)
        self.actionCurrentItemInLoop.setObjectName(u"actionCurrentItemInLoop")
        self.actionCurrentItemInLoop.setCheckable(True)
        self.actionSequential = QAction(MainWindow)
        self.actionSequential.setObjectName(u"actionSequential")
        self.actionSequential.setCheckable(True)
        self.actionLoop = QAction(MainWindow)
        self.actionLoop.setObjectName(u"actionLoop")
        self.actionLoop.setCheckable(True)
        self.actionRandom = QAction(MainWindow)
        self.actionRandom.setObjectName(u"actionRandom")
        self.actionRandom.setCheckable(True)
        self.centralwidgetMain = QWidget(MainWindow)
        self.centralwidgetMain.setObjectName(u"centralwidgetMain")
        self.verticalLayout = QVBoxLayout(self.centralwidgetMain)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.splitter = QSplitter(self.centralwidgetMain)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Horizontal)
        self.listWidgetAudioList = QListWidget(self.splitter)
        self.listWidgetAudioList.setObjectName(u"listWidgetAudioList")
        self.splitter.addWidget(self.listWidgetAudioList)
        self.layoutWidget = QWidget(self.splitter)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.verticalLayoutAudioMainArea = QVBoxLayout(self.layoutWidget)
        self.verticalLayoutAudioMainArea.setObjectName(u"verticalLayoutAudioMainArea")
        self.verticalLayoutAudioMainArea.setContentsMargins(0, 0, 0, 0)
        self.labelCurrentAudioName = QLabel(self.layoutWidget)
        self.labelCurrentAudioName.setObjectName(u"labelCurrentAudioName")
        self.labelCurrentAudioName.setAlignment(Qt.AlignCenter)

        self.verticalLayoutAudioMainArea.addWidget(self.labelCurrentAudioName)

        self.openGLWidgetAudioPlayShow = GLWidget(self.layoutWidget)
        self.openGLWidgetAudioPlayShow.setObjectName(u"openGLWidgetAudioPlayShow")

        self.verticalLayoutAudioMainArea.addWidget(self.openGLWidgetAudioPlayShow)

        self.horizontalSliderRateOfProcess = QSlider(self.layoutWidget)
        self.horizontalSliderRateOfProcess.setObjectName(u"horizontalSliderRateOfProcess")
        self.horizontalSliderRateOfProcess.setOrientation(Qt.Horizontal)

        self.verticalLayoutAudioMainArea.addWidget(self.horizontalSliderRateOfProcess)

        self.horizontalLayoutAudioOperationArea = QHBoxLayout()
        self.horizontalLayoutAudioOperationArea.setObjectName(u"horizontalLayoutAudioOperationArea")
        self.labelTimeTips = QLabel(self.layoutWidget)
        self.labelTimeTips.setObjectName(u"labelTimeTips")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTimeTips.sizePolicy().hasHeightForWidth())
        self.labelTimeTips.setSizePolicy(sizePolicy)

        self.horizontalLayoutAudioOperationArea.addWidget(self.labelTimeTips)

        self.horizontalSpacerLeft = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayoutAudioOperationArea.addItem(self.horizontalSpacerLeft)

        self.toolButtonPlayBackMode = QToolButton(self.layoutWidget)
        self.toolButtonPlayBackMode.setObjectName(u"toolButtonPlayBackMode")
        icon1 = QIcon()
        icon1.addFile(u":/icons/resources/loop.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButtonPlayBackMode.setIcon(icon1)
        self.toolButtonPlayBackMode.setIconSize(QSize(30, 30))

        self.horizontalLayoutAudioOperationArea.addWidget(self.toolButtonPlayBackMode)

        self.toolButtonStop = QToolButton(self.layoutWidget)
        self.toolButtonStop.setObjectName(u"toolButtonStop")
        self.toolButtonStop.setCursor(QCursor(Qt.PointingHandCursor))
        icon2 = QIcon()
        icon2.addFile(u":/icons/resources/stop.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButtonStop.setIcon(icon2)
        self.toolButtonStop.setIconSize(QSize(30, 30))

        self.horizontalLayoutAudioOperationArea.addWidget(self.toolButtonStop)

        self.toolButtonPre = QToolButton(self.layoutWidget)
        self.toolButtonPre.setObjectName(u"toolButtonPre")
        self.toolButtonPre.setCursor(QCursor(Qt.PointingHandCursor))
        icon3 = QIcon()
        icon3.addFile(u":/icons/resources/pre.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButtonPre.setIcon(icon3)
        self.toolButtonPre.setIconSize(QSize(30, 30))

        self.horizontalLayoutAudioOperationArea.addWidget(self.toolButtonPre)

        self.toolButtonBackward = QToolButton(self.layoutWidget)
        self.toolButtonBackward.setObjectName(u"toolButtonBackward")
        self.toolButtonBackward.setCursor(QCursor(Qt.PointingHandCursor))
        icon4 = QIcon()
        icon4.addFile(u":/icons/resources/backward.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButtonBackward.setIcon(icon4)
        self.toolButtonBackward.setIconSize(QSize(30, 30))

        self.horizontalLayoutAudioOperationArea.addWidget(self.toolButtonBackward)

        self.toolButtonPlayPause = QToolButton(self.layoutWidget)
        self.toolButtonPlayPause.setObjectName(u"toolButtonPlayPause")
        self.toolButtonPlayPause.setCursor(QCursor(Qt.PointingHandCursor))
        icon5 = QIcon()
        icon5.addFile(u":/icons/resources/play.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButtonPlayPause.setIcon(icon5)
        self.toolButtonPlayPause.setIconSize(QSize(50, 50))

        self.horizontalLayoutAudioOperationArea.addWidget(self.toolButtonPlayPause)

        self.toolButtonForward = QToolButton(self.layoutWidget)
        self.toolButtonForward.setObjectName(u"toolButtonForward")
        self.toolButtonForward.setCursor(QCursor(Qt.PointingHandCursor))
        icon6 = QIcon()
        icon6.addFile(u":/icons/resources/forward.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButtonForward.setIcon(icon6)
        self.toolButtonForward.setIconSize(QSize(30, 30))

        self.horizontalLayoutAudioOperationArea.addWidget(self.toolButtonForward)

        self.toolButtonNext = QToolButton(self.layoutWidget)
        self.toolButtonNext.setObjectName(u"toolButtonNext")
        self.toolButtonNext.setCursor(QCursor(Qt.PointingHandCursor))
        icon7 = QIcon()
        icon7.addFile(u":/icons/resources/next.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButtonNext.setIcon(icon7)
        self.toolButtonNext.setIconSize(QSize(30, 30))

        self.horizontalLayoutAudioOperationArea.addWidget(self.toolButtonNext)

        self.toolButtonVolume = QToolButton(self.layoutWidget)
        self.toolButtonVolume.setObjectName(u"toolButtonVolume")
        self.toolButtonVolume.setCursor(QCursor(Qt.PointingHandCursor))
        icon8 = QIcon()
        icon8.addFile(u":/icons/resources/volume.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButtonVolume.setIcon(icon8)
        self.toolButtonVolume.setIconSize(QSize(30, 30))
        self.toolButtonVolume.setAutoRaise(False)
        self.toolButtonVolume.setArrowType(Qt.NoArrow)

        self.horizontalLayoutAudioOperationArea.addWidget(self.toolButtonVolume)

        self.horizontalSliderVolume = QSlider(self.layoutWidget)
        self.horizontalSliderVolume.setObjectName(u"horizontalSliderVolume")
        self.horizontalSliderVolume.setCursor(QCursor(Qt.PointingHandCursor))
        self.horizontalSliderVolume.setOrientation(Qt.Horizontal)

        self.horizontalLayoutAudioOperationArea.addWidget(self.horizontalSliderVolume)

        self.labelVolume = QLabel(self.layoutWidget)
        self.labelVolume.setObjectName(u"labelVolume")

        self.horizontalLayoutAudioOperationArea.addWidget(self.labelVolume)

        self.horizontalSpacerRight = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayoutAudioOperationArea.addItem(self.horizontalSpacerRight)


        self.verticalLayoutAudioMainArea.addLayout(self.horizontalLayoutAudioOperationArea)

        self.verticalLayoutAudioMainArea.setStretch(1, 1)
        self.splitter.addWidget(self.layoutWidget)

        self.verticalLayout.addWidget(self.splitter)

        MainWindow.setCentralWidget(self.centralwidgetMain)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 838, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuOpenRecently = QMenu(self.menuFile)
        self.menuOpenRecently.setObjectName(u"menuOpenRecently")
        self.menuAutoSave = QMenu(self.menuFile)
        self.menuAutoSave.setObjectName(u"menuAutoSave")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuStepTime = QMenu(self.menuSettings)
        self.menuStepTime.setObjectName(u"menuStepTime")
        self.menuPlayBackRate = QMenu(self.menuSettings)
        self.menuPlayBackRate.setObjectName(u"menuPlayBackRate")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionOpenJsonFile)
        self.menuFile.addAction(self.actionOpenAudioFolder)
        self.menuFile.addAction(self.menuOpenRecently.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.menuAutoSave.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAutoSave.addAction(self.action0s)
        self.menuAutoSave.addAction(self.action60s)
        self.menuAutoSave.addAction(self.action120s)
        self.menuAutoSave.addAction(self.action180s)
        self.menuAutoSave.addAction(self.action300s)
        self.menuHelp.addAction(self.actionGetStarted)
        self.menuHelp.addAction(self.actionAbout)
        self.menuSettings.addAction(self.menuStepTime.menuAction())
        self.menuSettings.addAction(self.menuPlayBackRate.menuAction())
        self.menuStepTime.addAction(self.action1s)
        self.menuStepTime.addAction(self.action3s)
        self.menuStepTime.addAction(self.action5s)
        self.menuStepTime.addAction(self.action10s)
        self.menuStepTime.addAction(self.action30s)
        self.menuPlayBackRate.addAction(self.action0_5)
        self.menuPlayBackRate.addAction(self.action1_0)
        self.menuPlayBackRate.addAction(self.action1_5)
        self.menuPlayBackRate.addAction(self.action2_0)

        self.retranslateUi(MainWindow)

        # QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"AudioLabel", None))
        self.actionOpenFile.setText(QCoreApplication.translate("MainWindow", u"Open File...", None))
#if QT_CONFIG(shortcut)
        self.actionOpenFile.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpenAudioFolder.setText(QCoreApplication.translate("MainWindow", u"Open Audio Folder", None))
#if QT_CONFIG(shortcut)
        self.actionOpenAudioFolder.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.action12.setText(QCoreApplication.translate("MainWindow", u"12", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSaveAs.setText(QCoreApplication.translate("MainWindow", u"Save As...", None))
#if QT_CONFIG(shortcut)
        self.actionSaveAs.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.action0s.setText(QCoreApplication.translate("MainWindow", u"0 s", None))
        self.action60s.setText(QCoreApplication.translate("MainWindow", u"60 s", None))
        self.action120s.setText(QCoreApplication.translate("MainWindow", u"120 s", None))
        self.action180s.setText(QCoreApplication.translate("MainWindow", u"180 s", None))
        self.action300s.setText(QCoreApplication.translate("MainWindow", u"300 s", None))
        self.actionUserDefined.setText(QCoreApplication.translate("MainWindow", u"User Defined", None))
        self.actionGetStarted.setText(QCoreApplication.translate("MainWindow", u"Get Started", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionOpenAudioFiles.setText(QCoreApplication.translate("MainWindow", u"Open Audio Files", None))
#if QT_CONFIG(shortcut)
        self.actionOpenAudioFiles.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpenJsonFile.setText(QCoreApplication.translate("MainWindow", u"Open Json File", None))
#if QT_CONFIG(shortcut)
        self.actionOpenJsonFile.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+J", None))
#endif // QT_CONFIG(shortcut)
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
#if QT_CONFIG(shortcut)
        self.actionExit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.action0point25.setText(QCoreApplication.translate("MainWindow", u"0.25", None))
        self.action0point5.setText(QCoreApplication.translate("MainWindow", u"0.5", None))
        self.action0point75.setText(QCoreApplication.translate("MainWindow", u"0.75", None))
        self.action1point0.setText(QCoreApplication.translate("MainWindow", u"1.0", None))
        self.action1point25.setText(QCoreApplication.translate("MainWindow", u"1.25", None))
        self.action1point5.setText(QCoreApplication.translate("MainWindow", u"1.5", None))
        self.action1point75.setText(QCoreApplication.translate("MainWindow", u"1.75", None))
        self.action2point0.setText(QCoreApplication.translate("MainWindow", u"2.0", None))
        self.action2point5.setText(QCoreApplication.translate("MainWindow", u"2.5", None))
        self.action5s.setText(QCoreApplication.translate("MainWindow", u"5 s", None))
        self.action1s.setText(QCoreApplication.translate("MainWindow", u"1 s", None))
        self.action3s.setText(QCoreApplication.translate("MainWindow", u"3 s", None))
        self.action0_5.setText(QCoreApplication.translate("MainWindow", u"0.5", None))
        self.action0_75.setText(QCoreApplication.translate("MainWindow", u"0.75", None))
        self.action1_0.setText(QCoreApplication.translate("MainWindow", u"1.0", None))
        self.action1_25.setText(QCoreApplication.translate("MainWindow", u"1.25", None))
        self.action1_75.setText(QCoreApplication.translate("MainWindow", u"1.75", None))
        self.action1_5.setText(QCoreApplication.translate("MainWindow", u"1.5", None))
        self.action2_0.setText(QCoreApplication.translate("MainWindow", u"2.0", None))
        self.action2_5.setText(QCoreApplication.translate("MainWindow", u"2.5", None))
        self.action10s.setText(QCoreApplication.translate("MainWindow", u"10 s", None))
        self.action30s.setText(QCoreApplication.translate("MainWindow", u"30 s", None))
        self.actionCurrentItemOnce.setText(QCoreApplication.translate("MainWindow", u"0 Current Item Once", None))
        self.actionCurrentItemInLoop.setText(QCoreApplication.translate("MainWindow", u"1 Current Item In Loop", None))
        self.actionSequential.setText(QCoreApplication.translate("MainWindow", u"2 Sequential", None))
        self.actionLoop.setText(QCoreApplication.translate("MainWindow", u"3 Loop", None))
        self.actionRandom.setText(QCoreApplication.translate("MainWindow", u"4 Random", None))
        self.labelCurrentAudioName.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.labelTimeTips.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.toolButtonPlayBackMode.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonStop.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonPre.setText(QCoreApplication.translate("MainWindow", u"...", None))
#if QT_CONFIG(shortcut)
        self.toolButtonPre.setShortcut(QCoreApplication.translate("MainWindow", u"Up", None))
#endif // QT_CONFIG(shortcut)
        self.toolButtonBackward.setText(QCoreApplication.translate("MainWindow", u"...", None))
#if QT_CONFIG(shortcut)
        self.toolButtonBackward.setShortcut(QCoreApplication.translate("MainWindow", u"Left", None))
#endif // QT_CONFIG(shortcut)
        self.toolButtonPlayPause.setText(QCoreApplication.translate("MainWindow", u"...", None))
#if QT_CONFIG(shortcut)
        self.toolButtonPlayPause.setShortcut(QCoreApplication.translate("MainWindow", u"Space", None))
#endif // QT_CONFIG(shortcut)
        self.toolButtonForward.setText(QCoreApplication.translate("MainWindow", u"...", None))
#if QT_CONFIG(shortcut)
        self.toolButtonForward.setShortcut(QCoreApplication.translate("MainWindow", u"Right", None))
#endif // QT_CONFIG(shortcut)
        self.toolButtonNext.setText(QCoreApplication.translate("MainWindow", u"...", None))
#if QT_CONFIG(shortcut)
        self.toolButtonNext.setShortcut(QCoreApplication.translate("MainWindow", u"Down", None))
#endif // QT_CONFIG(shortcut)
        self.toolButtonVolume.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.labelVolume.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuOpenRecently.setTitle(QCoreApplication.translate("MainWindow", u"Open Recently", None))
        self.menuAutoSave.setTitle(QCoreApplication.translate("MainWindow", u"Auto Save", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuSettings.setTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.menuStepTime.setTitle(QCoreApplication.translate("MainWindow", u"Step Time", None))
        self.menuPlayBackRate.setTitle(QCoreApplication.translate("MainWindow", u"Play Back Rate", None))
    # retranslateUi

